services:
  frontend:
    build:
      target: dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 8000:8000
    env_file:
      - .env

  api:
    build:
      target: dev
    volumes:
      - ./api:/app
    ports:
      - 9000:80
    env_file:
      - .env

  postgres:
    env_file:
      - .env

volumes:
  node_modules:
