services:
  api:
    build:
      context: api
      target: prod
      args:
        DATABASE_URL: ${DATABASE_URL:?error}
    depends_on: [postgres]
    volumes:
      - auth:/app/data/auth:rw

  frontend:
    build:
      context: .
      target: prod
    depends_on: [api]

  postgres:
    image: postgres:16.4-alpine
    shm_size: 128m
    volumes:
      - postgres:/var/lib/postgresql:rw

volumes:
  postgres:
  auth:
